#!/bin/bash
set -eu
[ $# -lt 1  ] && echo "Use $0 only as an interpreter" 1>&2 && exit $LINENO
[ ! -f "$1" ] && echo "File '$1' does not exist"      1>&2 && exit $LINENO

d=$(dirname "$1")                         # Directory of source
c=$(mktemp "${TMPDIR-/tmp}/c99sh.XXXXXX") # Mangled source
x=$(mktemp "${TMPDIR-/tmp}/c99sh.XXXXXX") # Compiled binary
trap 'rm -f "$c" "$x"' EXIT               # Automatic cleanup

# Process an rcfile given its filename
declare -a flags=(${CFLAGS-} "-I$d")
declare -a logic=("$c" ${LDFLAGS-})
process_rcfile() {
  local i=0
  while read -r o; do
    echo "#line $((i+=1)) \"$1\" // $o" >> "$c"
    if   [[ $o =~ ^[[:space:]]*\$     ]]  # Whitespace
    then :
    elif [[ $o =~ ^[[:space:]]*#      ]]  # Preprocessor
    then echo "$o" >> "$c"
    elif [[ $o =~ ^[[:space:]]*-[lLR] ]]  # Linker flags
    then logic+=($o)
    elif [[ $o =~ ^[[:space:]]*-      ]]  # Compiler flags
    then flags+=($o)
    elif [[ $o =~ ^[[:space:]]*pkg-config[[:space:]]+--cflags ]]
    then flags+=($(eval $(printf %q "$o")))
    elif [[ $o =~ ^[[:space:]]*pkg-config[[:space:]]+--libs ]]
    then logic+=($(eval $(printf %q "$o")))
    elif [ -f "$o" ]                      # Linker target
    then logic+=($o)
    else printf "%s:%s:1 error: invalid c99sh\n\t%s\n\t^\n" "$1" "$i" "$o" 1>&2
         exit $LINENO
    fi
  done < "$1"
}

# Incorporate the first rcfile found
if   [ -f "$d/c99shrc" ]
then process_rcfile "$d/c99shrc"
elif [ -f "$HOME/.c99shrc" ]
then process_rcfile "$HOME/.c99shrc"
fi

# Prepare source files for "interpretation" by the compiler.
# Possibly swap shebang on first line of each with a line pragma so
#   (a) the source can be compiled, and
#   (b) errors and warnings show usable line details
echo "#line 1 \"$1\""                 >> "$c"
sed "1s|^#!.*\$|#line 2 \"$1\"|" "$1" >> "$c"

# Compile and execute with any remaining command line arguments
# TODO Can exec "$x" be used and the cleanup trap still work?
"${CC-cc}" -std=gnu99 -o "$x" "${flags[@]}" -x c "${logic[@]}" 1>&2
shift
"$x" "$@"
