# See https://circleci.com/docs/2.0/reusing-config/
version: 2.1

jobs:
  "Test":
    resource_class: small
    docker:
      - image: "cimg/base:2026.09"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libgsl-dev
            sudo apt-get install -y autotools-dev
            sudo apt-get install -y gcc-15 g++-15
      - run:
          name: Test c99sh
          command: |
            CC=/usr/bin/gcc-15 CXX=/usr/bin/g++-15 ./tests

workflows:
  build:
    jobs:
      - "Test"
