#!/usr/bin/env bash
set -eux
# cxxsh test driver relying upon cxxshrc in the same directory
cd "${0%/*}"

"${CXX-c++}" --version
"${CXX-c++}" -std=gnu++17 -dM -E -x c++ - </dev/null | grep __cplusplus

./hello

./headers-c11

./headers-c++17

./headers-both

./heredoc

./shebang.cpp
g++ ./shebang.cpp
./a.out
rm a.out

../cxxsh -vv -x a.out shebang.cpp
./a.out
rm a.out

./quicktest.cpp
g++ -c ./quicktest.cpp
rm ./quicktest.o
