#!/bin/bash -eux

# C11 inside bash using a here document (in scripts skip the ../ prefix).
../c11sh -sm <<HERE
#if __STDC_VERSION__ != 201112L
#error C11 not detected
#endif
printf("Hello, world!\n");
HERE

# C99 requiring proper operation of -L for successful building
../c99sh -vvv <<HERE
#include <pthread.h>
int main() {
    pthread_exit(0L);
}
HERE
