#!/bin/bash -eux
# c99sh test driver relying upon c99shrc in the same directory
cd "${0%/*}"

./hello

./oneliner

./heredoc

./shebang.c
gcc ./shebang.c
./a.out
rm a.out

../c99sh -vv -x a.out shebang.c
./a.out
rm a.out

./quicktest.c
gcc -c ./quicktest.c
rm ./quicktest.o
