#!/usr/bin/env bash
set -eux
# c99sh test driver relying upon c99shrc in the same directory
cd "${0%/*}"

./hello

./oneliner

./heredoc


# Build
rm -f ./a.out
gcc ./shebang.c
# No arguments
./a.out
./shebang.c
# Some arguments
./a.out Foo Bar
./shebang.c Foo Bar
# Cleanup
rm a.out

rm -f b.out
../c99sh -vv -x b.out shebang.c
./b.out
rm b.out

./quicktest.c
gcc -c ./quicktest.c
rm ./quicktest.o
